#Site configuration
title: T's Site
name:  T's Site
author: Taapas Agrawal
work:  Software Developer | AI Enthusiast
year: 2019

# Navigation
nav1: "About"
nav2: "Things I Can Do"
nav3: "A Few Accomplishments"
nav4: "Blogs"

# Section1
sec1: "About Me"
sec2: "Just a fellow Human being."
sec3: "I am a 3rd year Undergraduate student at Indian Institute Of Technology Kharagpur, in India.
       I'm pursuing a major in Applied Geology and a minor in Mathematics and Computing. I'm a robotics and AI enthusiast. 
       I've been coding in C and C++ for over two years and in Python for a year and am proficient in all three of them now.
       I am a part of Kharagpur Robosoccer Students' Group(KRSSG)and  Kharagpur Open Source Society
       My interests span Software Development, Machine Learning, Reinforcement Learning,
       Version Control Systems, Technical Writing, and Gaming."
# Section 2
sec4: "Things I Can Do"
sec5: "These are a few things I can do. No kidding!"
icon1: "fas fa-code"
icont1: "Write some code"
icon2: "fa-cubes"
icont2: "Stack small boxes"
icon3: "fa-book"
icont3: "Read books and stuff"
icon4: "fa-coffee"
icont4: "Drink much coffee"
icon5: "fa-bolt"
icont5: "Lightning bolt"
icon6: "fa-users"
icont6: "Shadow clone technique"

# Section 3
sec6: "A Few Accomplishments"
sec8: "Student Developer at Google Summer of Code"
sec9: "Working on a project regarding implementation of a unified abort and continue command for multistep operations.
Organization: ğ— ğ—²ğ—¿ğ—°ğ˜‚ğ—¿ğ—¶ğ—®ğ—¹, Python Software Foundation
Mentors: Pulkit Goyal, Sangeet Kumar Mishra, Susheel Khanchi
Project abstract: https://summerofcode.withgoogle.com/projects/#5132139832541184"
sec10: "Humanoid Team Head at KRSSG"
sec11: "My work is to develop Artificial Intelligence for creating a team of autonomous humanoid robots play soccer. We represent India in an international robotics event RoboCup by taking part in Robosoccer 3D simulation league. My work experience includes optimization techniques, Reinforcement Learning, multi-agent coordination, and logic."
sec12: "Executive Head at KOSS"
sec13: "We are a group of Open Source Enthusiasts who focus on something more preliminary and relevant, â€ğ—” ğ—Ÿğ—¼ğ˜ƒğ—² ğ—³ğ—¼ğ—¿ ğ—–ğ—¼ğ—±ğ—¶ğ—»ğ—´â€.
Every year KOSS plans to hold events for familiarizing students with UNIX tools, Linux environment, Git Development Workflow, practice Algorithms and Data Structures, besides conducting workshops on GUI programming, Web development, Android application Development and Hackathons. "

#Section 4
sec14: "Blogs"
sec15: "links"

# Social Links
facebook: assassinX.taapas
twitter:  AgrawalTaapas
#google: username
#instagram: username
#pinterest: username
linkedin: taapas-agrawal-956110152
#youtube: username
#spotify: username
#lastfm: username
github: taapasX28
#stackoverflow: username
#quora: username
#reddit: username
medium: taapasagrawal
#vimeo: username
#keybase: username
email: taapas2897@gmail.com

